### PR TITLE
Add eslint

### LINKED ISSUE #38: Add a linter

### PR DESCRIPTION
**Pull request by marlo-longley**
Fixes #38 

I globally disabled `"@typescript-eslint/no-explicit-any"` in the config because it was generating a ton of violations all over the app, and in `index.ts`, I disabled `/* eslint-disable @typescript-eslint/no-unused-vars */` for the whole file. This is because every line such as `user(parent, args, { dataSources }, info) ...` has an unused arg for parent and info, but I think we need them in those positions.

### CODE REVIEW

**Comment by cbeer** [comment]
Can we wire this into CI too?

**Comment by marlo-longley** [comment]
@cbeer I added a CI step that I think will work

**Comment by cbeer** [comment]
Thanks -- it also looks like there's some merge conflicts in the package.lock?

**Comment by marlo-longley** [comment]
@cbeer thank you for catching that. I pushed a new package-lock. It is a large diff but it's just the result of running `npm install` with the new package.json.

**Comment by cbeer** [comment]
I'm not going to think too hard about how a simpler linter could possibly have that many dependencies 🙈

**Pull request merged**
